name: "VARSTACK"
description: ""

url: "http://www.varstack.com"

paginate: 10
markdown: rdiscount
permalink: pretty
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-feed
